### ISSUE TITLE
Template engine

### ISSUE THREAD

**Issue by tecc** [yoyosource/YAPI#3]
I'd love a template engine for YAPI. Nothing special to it, just a template engine.

**Comment by yoyosource** [comment]
Hello Technotype0
I like you idea but I have one question.
What should this template engine be able to do? so what are the features you want?

**Comment by tecc** [comment]
It's a template engine. For example, I'll use Apache Velocity. You create your engine, and then some text (for example some HTML:
```html
<div class="product">
<h2>${product.name}</h2>
<h3>${product.price}</h3>
</div>
```
), add your values (in this case `product`), and pass the text through the engine which then finally comes out to something like this:
```html
<div class="product">
<h2>Banana</h2>
<h3>2</h2>
</div>```

**Comment by yoyosource** [comment]
Oh ok. I will look into it and see what I can do

**Comment by yoyosource** [comment]
Should this System just replace Values like String Integer and so or should it also be able to call methods on this Types.

**Comment by tecc** [comment]
Yes, naturally. That's an integral part of a template engine.

**Comment by yoyosource** [comment]
Ok. I will look into it. Thanks for the suggestion

**Comment by yoyosource** [comment]
Hello TechnotypeO,
I will implement variable mode and execution mode. So variable mode is just replacement of variables and execution mode is for executing methods on those types.

**Comment by yoyosource** [comment]
For now variable mode is implemented and should work see package `yapi.string.templateengine`
