### ISSUE TITLE
FastEncryptionSymetric

### ISSUE THREAD

**Issue by Chaoscaot** [yoyosource/YAPI#6]
**Describe the bug**
The Encryption goes in en infinity loop if file is too small.
 
**To Reproduce**
1. Create a file under 1 mega byte
2. Encrypt it

**Expected behavior**
That the file gets encrypted.

**Additional context**
--

EDIT
- No swearing

**Comment by yoyosource** [comment]
What is your block size? Is it smaller than your file size or larger?

**Comment by Chaoscaot** [comment]
Idk

**Comment by yoyosource** [comment]
You are a Collaborator, you should know how to code. Couldn't you look it up? How did you set it up? Can you give me your example code?

**Comment by yoyosource** [comment]
Maven Release 1.3-10 should fix this issue.
