### ISSUE TITLE
Windows Error.

### ISSUE THREAD

**Issue by ghost** [yoyosource/YAPI#7]
Hello, there is a problem with Windows regarding your Fast Encryption. I do not know how it is in other operating systems in any case there is an error with me under Windows. The processing rate becomes lower in the running process. I ask for no answer, just take note and edit if necessary.
LG QDev

**Comment by yoyosource** [comment]
As I tried to reproduce this Error on MacOS yesterday and I wasn't able to do so in an hour. I think this Error only occurs on Windows. I will have a look into the Code and will come back to you to test things. I hope that's not a problem.

Regards, yoyosource
